CREATE DATABASE bdprjRH;

USE bdprjRH;

CREATE TABLE gerente(
	id_gerente VARCHAR(10) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	nome VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cpf VARCHAR(15) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI UNIQUE NOT NULL,
	CONSTRAINT pkid_gerente PRIMARY KEY(id_gerente));

CREATE TABLE empregado(
	id_empregado VARCHAR(10) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	nome VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cpf VARCHAR(15) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI UNIQUE NOT NULL,
	id_gerente VARCHAR(20) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	CONSTRAINT pkid_empregado PRIMARY KEY(id_empregado),
	CONSTRAINT fkid_gerente FOREIGN KEY(id_gerente) REFERENCES gerente(id_gerente));	

CREATE TABLE departamento(
	id_departamento VARCHAR(10) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	nome VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cnpj VARCHAR(20) UNIQUE NOT NULL,
	CONSTRAINT pkid_departamento PRIMARY KEY(id_departamento));
