CREATE DATABASE bdprjRH;

USE bdprjRH;	

CREATE TABLE departamento(
	id_departamento VARCHAR(10) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	nome VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cnpj INT UNIQUE NOT NULL,
	CONSTRAINT pkid_departamento PRIMARY KEY(id_departamento));

CREATE TABLE funcionario(
	id_funcionario VARCHAR(10) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	nome VARCHAR(50) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cpf VARCHAR(15) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI UNIQUE NOT NULL,
	cod_departamento VARCHAR(20) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	CONSTRAINT pkid_funcionario PRIMARY KEY(id_funcionario),
	CONSTRAINT fkcod_departamento FOREIGN KEY(cod_departamento) REFERENCES departamento(id_departamento));
